version: '3'
services:
  postgres:
    build:
      dockerfile: Dockerfile
      context: ./postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client/src:/app/src
      - ./client/public:/app/public
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true