FROM node:alpine

WORKDIR /app

COPY package.json /app

RUN npm config set unsafe-perm true

RUN npm install --force

RUN chown -R node /app/node_modules

USER node

COPY . /app

CMD ["npm", "run", "start"]